### ISSUE TITLE
There is an old privacy policy as PDF 

### ISSUE THREAD

**Issue by robertoostenveld** [donders-research-data-management/rdr-configurable-content-donders#77]
On https://data-acc.ru.nl/doc/help/references.html I noticed a PDF download, whereas on https://data-acc.ru.nl/doc/privacy_policy.html there is also a direct link to an HTML version. I believe the PDF version to be the older version, as it mentions

_The DI RDM repository stores, amongst others, human data, and for these human data, there also is a privacy policy. The latter policy is a part of the Protocol for Researchers. The privacy policy outlined here pertains to the data the repository stores about its users._

at the start. This does not apply any more in this particulay way.

I propose to remove the PDF version from the References page. Perhaps we should remove the whole page (now that it would be empty) or start thinking what else we want to refer to.  @jesask and @miriamkos what do you think?

Note that this applies both to the Donders one, and to the RDR (acceptance) one.

**Comment by jesask** [comment]
Hi @robertoostenveld  fyi @miriamkos I agree about deleting the PDF document but I think we must point to the privacy policy explicitly on the references page (as who would be able to find the location of the .html version?)

I propose to add the following about changes of the privacy policy, as here copied (if agreed, @hurngchunlee can you deploy to production?)

_This `privacy policy <https://data.donders.ru.nl/doc/privacy_policy.html>`_ describes how the repository processes and stores data about its users. 

This privacy policy may change from time to time. If we make a change to this policy that we believe impacts your rights, you will be notified. By continuing usage of the repository after changes have become effective, you agree to be bound by the new privacy policy.__

**Comment by robertoostenveld** [comment]
There is a link to the privacy policy in the footer of the website, which means it is on every page already.

<img width="649" alt="Screenshot 2020-05-18 at 14 38 21" src="https://user-images.githubusercontent.com/899043/82213989-548b4e00-9915-11ea-8270-bd0bf4966cd2.png">

That is also where most other websites have it (or approximately), see e.g. https://www.ru.nl and https://www.nu.nl. Hence I think that it does not have to be on the references page as well. Personally I would also not go searching in the references of the help section to find the privacy policy.

Any statements regarding the privacy policy (e.g. that it can change in the future, and that people will receive an email in that case, and that people implicitly agree when continueing to use the site) should be made on the page itself, i.e. within https://github.com/donders-research-data-management/rdr-configurable-content-donders/blob/master/doc/privacy_policy.html. The content of that file is also shown explicitly whenever people sign up. Note that adding this sentence itself is a rather minor change, and I would not send around an email to all 1000+ people with this small change.

**Comment by hurngchunlee** [comment]
@jesask I have deployed your change on production: see https://data.donders.ru.nl/doc/help/references.html

**Comment by miriamkos** [comment]
I agree with Robert in this

**Comment by jesask** [comment]
@hurngchunlee I removed the content of the references page, left the references.rst, (in case it will be used in the future) and removed the menu "references" item from the toc and index. Can you deploy again? Thanks.

@ all I did not make any changes to the privacy policy now. If you think it's a good idea to add something similar to what I suggested, you can add it to the agenda for the next DI RDM meeting.

**Comment by hurngchunlee** [comment]
@jesask since your changes have been deployed to the production, I think this issue can be closed, right?

**Comment by jesask** [comment]
@hurngchunlee yes!
