### ISSUE TITLE
Update manuals: onegini -> eduID

### ISSUE THREAD

**Issue by jesask** [donders-research-data-management/rdr-configurable-content-donders#78]
Onegini will cease to exist per July 1st 2020; instead, eduIDs will be used to allow access to SURF supported facilities for those without educational account; accounts to be migrated from onegini to eduID by users themselves. This has consequences for login to DR -> update DR manual and faq pages concerning login

**Comment by miriamkos** [comment]
Ok, good point. Shall we discuss this upcoming monday in our monthly DI stewards meeting?

**Comment by hurngchunlee** [comment]
@jesask @miriamkos given that the manual concerning eduID has been made online, shall we close this issue?

**Comment by jesask** [comment]
@hurngchunlee again, good point, let's close
