### ISSUE TITLE
remove old branches

### ISSUE THREAD

**Issue by robertoostenveld** [donders-research-data-management/rdr-configurable-content-donders#80]
to reduce clutter, I propose that all old and completely merged branches are deleted.

<img width="979" alt="Screenshot 2020-10-28 at 09 16 17" src="https://user-images.githubusercontent.com/899043/97409678-531b7400-18fe-11eb-94d4-7fad9d38501e.png">

**Comment by hurngchunlee** [comment]
I agree with it and have done it.
